### ISSUE TITLE
Yaml with multiple documents

### ISSUE THREAD

**Issue by theduke** [sclevine/yj#24] opened 2021-08-26 10:18 UTC
Trying to convert a `.yaml` file with multiple documents (seperated by `---`) will only convert the first document and discard the rest.

It would be nice to get output for all of them, potentially in an array.

**Comment by sclevine** [comment] 2021-09-29 05:14
Duplicate of https://github.com/sclevine/yj/issues/14

**Closed** 2021-09-29 10:08 UTC
